CREATE TABLE `system_settings` (
    `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
    `public_id` text NOT NULL,
    `organization_id` text NOT NULL,
    `version` integer NOT NULL,
    `is_current` integer DEFAULT TRUE NOT NULL,
    `default_loan_product_id` integer,
    `default_payment_frequency` text NOT NULL,
    `enabled_payment_frequencies` text NOT NULL,
    `allow_partial_payments` integer DEFAULT TRUE NOT NULL,
    `allow_advance_payments` integer DEFAULT TRUE NOT NULL,
    `require_renewal_approval` integer DEFAULT TRUE NOT NULL,
    `borrower_tag_policy` text NOT NULL,
    `idempotency_key` text,
    `request_fingerprint` text,
    `created_by_user_id` text NOT NULL,
    `created_at` integer DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)) NOT NULL,
    CONSTRAINT `system_settings_fk_organization` FOREIGN KEY (`organization_id`) REFERENCES `organization`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `system_settings_fk_default_loan_product` FOREIGN KEY (`organization_id`,`default_loan_product_id`) REFERENCES `loan_product`(`organization_id`,`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `system_settings_fk_created_by_member` FOREIGN KEY (`organization_id`,`created_by_user_id`) REFERENCES `member`(`organization_id`,`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `system_settings_organization_id_id_unique` UNIQUE(`organization_id`,`id`),
    CONSTRAINT `system_settings_organization_id_public_id_unique` UNIQUE(`organization_id`,`public_id`),
    CONSTRAINT `system_settings_organization_id_version_unique` UNIQUE(`organization_id`,`version`),
    CONSTRAINT `system_settings_organization_id_idempotency_key_unique` UNIQUE(`organization_id`,`idempotency_key`),
    CONSTRAINT `system_settings_check_version` CHECK(`version` > 0),
    CONSTRAINT `system_settings_check_default_frequency` CHECK(`default_payment_frequency` IN ('DAILY', 'WEEKLY', 'MONTHLY')),
    CONSTRAINT `system_settings_check_enabled_payment_frequencies` CHECK(json_valid(`enabled_payment_frequencies`) AND json_type(`enabled_payment_frequencies`) = 'array' AND json_array_length(`enabled_payment_frequencies`) > 0),
    CONSTRAINT `system_settings_check_borrower_tag_policy` CHECK(json_valid(`borrower_tag_policy`) AND json_type(`borrower_tag_policy`) = 'object'),
    CONSTRAINT `system_settings_check_idempotency_fingerprint` CHECK((`idempotency_key` IS NULL AND `request_fingerprint` IS NULL) OR (`idempotency_key` IS NOT NULL AND length(`request_fingerprint`) = 64 AND `request_fingerprint` NOT GLOB '*[^0-9a-f]*'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `system_settings_unique_current` ON `system_settings` (`organization_id`) WHERE `system_settings`.`is_current` = TRUE;
