CREATE UNIQUE INDEX `loan_formula_profile_organization_id_id_unique` ON `loan_formula_profile` (`organization_id`, `id`);
--> statement-breakpoint
CREATE TABLE `loan_product` (
    `id` integer PRIMARY KEY AUTOINCREMENT,
    `public_id` text NOT NULL,
    `organization_id` text NOT NULL,
    `formula_profile_id` integer NOT NULL,
    `name` text NOT NULL,
    `is_active` integer DEFAULT true NOT NULL,
    `interest_method` text NOT NULL,
    `interest_rate_basis_points` integer DEFAULT 0 NOT NULL,
    `fixed_interest_amount_minor` integer,
    `term_days` integer NOT NULL,
    `payment_frequency` text NOT NULL,
    `installment_count` integer NOT NULL,
    `timezone` text DEFAULT 'Asia/Manila' NOT NULL,
    `rounding_mode` text NOT NULL,
    `final_installment_residue_policy` text NOT NULL,
    `renewal_settlement_method` text NOT NULL,
    `partial_credit_policy` text NOT NULL,
    `min_completed_installments` integer DEFAULT 0 NOT NULL,
    `allow_renewal_principal_change` integer DEFAULT false NOT NULL,
    `minimum_principal_amount_minor` integer NOT NULL,
    `maximum_principal_amount_minor` integer NOT NULL,
    `idempotency_key` text,
    `created_by_user_id` text NOT NULL,
    `updated_by_user_id` text NOT NULL,
    `created_at` integer DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)) NOT NULL,
    `updated_at` integer DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)) NOT NULL,
    CONSTRAINT `loan_product_organization_id_id_unique` UNIQUE(`organization_id`, `id`),
    CONSTRAINT `loan_product_organization_id_public_id_unique` UNIQUE(`organization_id`, `public_id`),
    CONSTRAINT `loan_product_organization_id_idempotency_key_unique` UNIQUE(`organization_id`, `idempotency_key`),
    CONSTRAINT `loan_product_fk_organization` FOREIGN KEY (`organization_id`) REFERENCES `organization`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `loan_product_fk_formula_profile` FOREIGN KEY (`organization_id`, `formula_profile_id`) REFERENCES `loan_formula_profile`(`organization_id`, `id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `loan_product_fk_created_by_member` FOREIGN KEY (`organization_id`, `created_by_user_id`) REFERENCES `member`(`organization_id`, `user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `loan_product_fk_updated_by_member` FOREIGN KEY (`organization_id`, `updated_by_user_id`) REFERENCES `member`(`organization_id`, `user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `loan_product_check_name` CHECK(length(trim(`name`)) > 0),
    CONSTRAINT `loan_product_check_interest` CHECK((`interest_method` = 'FLAT_PERCENTAGE' AND `interest_rate_basis_points` >= 0 AND `fixed_interest_amount_minor` IS NULL) OR (`interest_method` = 'FIXED_AMOUNT' AND `interest_rate_basis_points` = 0 AND `fixed_interest_amount_minor` IS NOT NULL AND `fixed_interest_amount_minor` >= 0)),
    CONSTRAINT `loan_product_check_term_days` CHECK(`term_days` > 0),
    CONSTRAINT `loan_product_check_payment_frequency` CHECK(`payment_frequency` IN ('DAILY', 'WEEKLY', 'MONTHLY')),
    CONSTRAINT `loan_product_check_installment_count` CHECK(`installment_count` > 0),
    CONSTRAINT `loan_product_check_timezone` CHECK(`timezone` = 'Asia/Manila'),
    CONSTRAINT `loan_product_check_rounding_mode` CHECK(`rounding_mode` IN ('HALF_UP', 'DOWN', 'UP')),
    CONSTRAINT `loan_product_check_final_installment_residue_policy` CHECK(`final_installment_residue_policy` = 'LAST_INSTALLMENT_ABSORBS_RESIDUE'),
    CONSTRAINT `loan_product_check_renewal_settlement_method` CHECK(`renewal_settlement_method` IN ('COMPLETED_INSTALLMENT_BALANCE', 'EXACT_OUTSTANDING_BALANCE')),
    CONSTRAINT `loan_product_check_partial_credit_policy` CHECK(`partial_credit_policy` IN ('CARRY_FORWARD', 'APPLY_TO_SETTLEMENT', 'REFUND', 'MANUAL_REVIEW')),
    CONSTRAINT `loan_product_check_min_completed_installments` CHECK(`min_completed_installments` >= 0 AND `min_completed_installments` <= `installment_count`),
    CONSTRAINT `loan_product_check_principal_range` CHECK(`minimum_principal_amount_minor` > 0 AND `maximum_principal_amount_minor` >= `minimum_principal_amount_minor`)
);
--> statement-breakpoint
CREATE TABLE `loan` (
    `id` integer PRIMARY KEY AUTOINCREMENT,
    `public_id` text NOT NULL,
    `organization_id` text NOT NULL,
    `loan_number` text NOT NULL,
    `borrower_id` integer NOT NULL,
    `loan_product_id` integer NOT NULL,
    `formula_profile_id` integer NOT NULL,
    `loan_product_name_snapshot` text NOT NULL,
    `formula_profile_name_snapshot` text NOT NULL,
    `formula_profile_version_snapshot` integer NOT NULL,
    `interest_method` text NOT NULL,
    `interest_rate_basis_points` integer DEFAULT 0 NOT NULL,
    `fixed_interest_amount_minor` integer,
    `principal_amount_minor` integer NOT NULL,
    `minimum_principal_amount_minor_snapshot` integer NOT NULL,
    `maximum_principal_amount_minor_snapshot` integer NOT NULL,
    `interest_amount_minor` integer NOT NULL,
    `total_payable_amount_minor` integer NOT NULL,
    `term_days` integer NOT NULL,
    `payment_frequency` text NOT NULL,
    `installment_count` integer NOT NULL,
    `installment_amount_minor` integer NOT NULL,
    `daily_payment_amount_minor` integer NOT NULL,
    `timezone` text DEFAULT 'Asia/Manila' NOT NULL,
    `rounding_mode` text NOT NULL,
    `final_installment_residue_policy` text NOT NULL,
    `renewal_settlement_method` text NOT NULL,
    `partial_credit_policy` text NOT NULL,
    `min_completed_installments` integer DEFAULT 0 NOT NULL,
    `allow_renewal_principal_change` integer DEFAULT false NOT NULL,
    `release_date` text,
    `first_payment_date` text NOT NULL,
    `expected_completion_date` text NOT NULL,
    `total_amount_paid_minor` integer DEFAULT 0 NOT NULL,
    `completed_installment_count` integer DEFAULT 0 NOT NULL,
    `partial_payment_credit_minor` integer DEFAULT 0 NOT NULL,
    `actual_outstanding_balance_minor` integer NOT NULL,
    `status` text DEFAULT 'DRAFT' NOT NULL,
    `create_idempotency_key` text,
    `release_idempotency_key` text,
    `created_by_user_id` text NOT NULL,
    `updated_by_user_id` text NOT NULL,
    `approved_by_user_id` text,
    `approved_at` integer,
    `released_by_user_id` text,
    `released_at` integer,
    `created_at` integer DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)) NOT NULL,
    `updated_at` integer DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)) NOT NULL,
    CONSTRAINT `loan_organization_id_id_unique` UNIQUE(`organization_id`, `id`),
    CONSTRAINT `loan_organization_id_public_id_unique` UNIQUE(`organization_id`, `public_id`),
    CONSTRAINT `loan_organization_id_loan_number_unique` UNIQUE(`organization_id`, `loan_number`),
    CONSTRAINT `loan_organization_id_create_idempotency_key_unique` UNIQUE(`organization_id`, `create_idempotency_key`),
    CONSTRAINT `loan_organization_id_release_idempotency_key_unique` UNIQUE(`organization_id`, `release_idempotency_key`),
    CONSTRAINT `loan_fk_organization` FOREIGN KEY (`organization_id`) REFERENCES `organization`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `loan_fk_borrower` FOREIGN KEY (`organization_id`, `borrower_id`) REFERENCES `borrower`(`organization_id`, `id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `loan_fk_product` FOREIGN KEY (`organization_id`, `loan_product_id`) REFERENCES `loan_product`(`organization_id`, `id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `loan_fk_formula_profile` FOREIGN KEY (`organization_id`, `formula_profile_id`) REFERENCES `loan_formula_profile`(`organization_id`, `id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `loan_fk_created_by_member` FOREIGN KEY (`organization_id`, `created_by_user_id`) REFERENCES `member`(`organization_id`, `user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `loan_fk_updated_by_member` FOREIGN KEY (`organization_id`, `updated_by_user_id`) REFERENCES `member`(`organization_id`, `user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `loan_fk_approved_by_member` FOREIGN KEY (`organization_id`, `approved_by_user_id`) REFERENCES `member`(`organization_id`, `user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `loan_fk_released_by_member` FOREIGN KEY (`organization_id`, `released_by_user_id`) REFERENCES `member`(`organization_id`, `user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `loan_check_loan_number` CHECK(length(trim(`loan_number`)) > 0),
    CONSTRAINT `loan_check_snapshot_names` CHECK(length(trim(`loan_product_name_snapshot`)) > 0 AND length(trim(`formula_profile_name_snapshot`)) > 0 AND `formula_profile_version_snapshot` > 0),
    CONSTRAINT `loan_check_interest` CHECK((`interest_method` = 'FLAT_PERCENTAGE' AND `interest_rate_basis_points` >= 0 AND `fixed_interest_amount_minor` IS NULL) OR (`interest_method` = 'FIXED_AMOUNT' AND `interest_rate_basis_points` = 0 AND `fixed_interest_amount_minor` IS NOT NULL AND `fixed_interest_amount_minor` >= 0)),
    CONSTRAINT `loan_check_principal_range` CHECK(`minimum_principal_amount_minor_snapshot` > 0 AND `maximum_principal_amount_minor_snapshot` >= `minimum_principal_amount_minor_snapshot` AND `principal_amount_minor` >= `minimum_principal_amount_minor_snapshot` AND `principal_amount_minor` <= `maximum_principal_amount_minor_snapshot`),
    CONSTRAINT `loan_check_amounts` CHECK(`interest_amount_minor` >= 0 AND `total_payable_amount_minor` = `principal_amount_minor` + `interest_amount_minor` AND `installment_amount_minor` > 0 AND `daily_payment_amount_minor` > 0 AND `total_amount_paid_minor` >= 0 AND `partial_payment_credit_minor` >= 0 AND `actual_outstanding_balance_minor` >= 0 AND `actual_outstanding_balance_minor` = `total_payable_amount_minor` - `total_amount_paid_minor`),
    CONSTRAINT `loan_check_term_days` CHECK(`term_days` > 0),
    CONSTRAINT `loan_check_payment_frequency` CHECK(`payment_frequency` IN ('DAILY', 'WEEKLY', 'MONTHLY')),
    CONSTRAINT `loan_check_installment_count` CHECK(`installment_count` > 0),
    CONSTRAINT `loan_check_completed_installment_count` CHECK(`completed_installment_count` >= 0 AND `completed_installment_count` <= `installment_count`),
    CONSTRAINT `loan_check_timezone` CHECK(`timezone` = 'Asia/Manila'),
    CONSTRAINT `loan_check_rounding_mode` CHECK(`rounding_mode` IN ('HALF_UP', 'DOWN', 'UP')),
    CONSTRAINT `loan_check_final_installment_residue_policy` CHECK(`final_installment_residue_policy` = 'LAST_INSTALLMENT_ABSORBS_RESIDUE'),
    CONSTRAINT `loan_check_renewal_settlement_method` CHECK(`renewal_settlement_method` IN ('COMPLETED_INSTALLMENT_BALANCE', 'EXACT_OUTSTANDING_BALANCE')),
    CONSTRAINT `loan_check_partial_credit_policy` CHECK(`partial_credit_policy` IN ('CARRY_FORWARD', 'APPLY_TO_SETTLEMENT', 'REFUND', 'MANUAL_REVIEW')),
    CONSTRAINT `loan_check_min_completed_installments` CHECK(`min_completed_installments` >= 0 AND `min_completed_installments` <= `installment_count`),
    CONSTRAINT `loan_check_dates` CHECK(length(`first_payment_date`) = 10 AND `first_payment_date` GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' AND length(`expected_completion_date`) = 10 AND `expected_completion_date` GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' AND (`release_date` IS NULL OR (length(`release_date`) = 10 AND `release_date` GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'))),
    CONSTRAINT `loan_check_approval_actor` CHECK((`approved_by_user_id` IS NULL AND `approved_at` IS NULL) OR (`approved_by_user_id` IS NOT NULL AND `approved_at` IS NOT NULL)),
    CONSTRAINT `loan_check_release_actor` CHECK((`released_by_user_id` IS NULL AND `released_at` IS NULL AND `release_date` IS NULL) OR (`released_by_user_id` IS NOT NULL AND `released_at` IS NOT NULL AND `release_date` IS NOT NULL)),
    CONSTRAINT `loan_check_status` CHECK(`status` IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'ACTIVE', 'OVERDUE', 'RENEWED', 'FULLY_PAID', 'CANCELLED', 'WRITTEN_OFF')),
    CONSTRAINT `loan_check_lifecycle` CHECK((`status` IN ('DRAFT', 'PENDING_APPROVAL', 'CANCELLED') AND `approved_by_user_id` IS NULL AND `approved_at` IS NULL AND `released_by_user_id` IS NULL AND `released_at` IS NULL AND `release_date` IS NULL) OR (`status` = 'APPROVED' AND `approved_by_user_id` IS NOT NULL AND `approved_at` IS NOT NULL AND `released_by_user_id` IS NULL AND `released_at` IS NULL AND `release_date` IS NULL) OR (`status` IN ('ACTIVE', 'OVERDUE', 'RENEWED', 'FULLY_PAID', 'WRITTEN_OFF') AND `approved_by_user_id` IS NOT NULL AND `approved_at` IS NOT NULL AND `released_by_user_id` IS NOT NULL AND `released_at` IS NOT NULL AND `release_date` IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE `loan_installment` (
    `id` integer PRIMARY KEY AUTOINCREMENT,
    `public_id` text NOT NULL,
    `organization_id` text NOT NULL,
    `loan_id` integer NOT NULL,
    `installment_number` integer NOT NULL,
    `payment_frequency` text NOT NULL,
    `period_start` text NOT NULL,
    `period_end` text NOT NULL,
    `due_date` text NOT NULL,
    `amount_due_minor` integer NOT NULL,
    `amount_paid_minor` integer DEFAULT 0 NOT NULL,
    `paid_at` integer,
    `status` text DEFAULT 'UPCOMING' NOT NULL,
    CONSTRAINT `loan_installment_organization_id_public_id_unique` UNIQUE(`organization_id`, `public_id`),
    CONSTRAINT `loan_installment_organization_id_loan_id_number_unique` UNIQUE(`organization_id`, `loan_id`, `installment_number`),
    CONSTRAINT `loan_installment_fk_loan` FOREIGN KEY (`organization_id`, `loan_id`) REFERENCES `loan`(`organization_id`, `id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `loan_installment_check_number` CHECK(`installment_number` > 0),
    CONSTRAINT `loan_installment_check_payment_frequency` CHECK(`payment_frequency` IN ('DAILY', 'WEEKLY', 'MONTHLY')),
    CONSTRAINT `loan_installment_check_dates` CHECK(length(`period_start`) = 10 AND `period_start` GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' AND length(`period_end`) = 10 AND `period_end` GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' AND length(`due_date`) = 10 AND `due_date` GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' AND `period_start` <= `period_end` AND `period_end` <= `due_date`),
    CONSTRAINT `loan_installment_check_amounts` CHECK(`amount_due_minor` > 0 AND `amount_paid_minor` >= 0 AND `amount_paid_minor` <= `amount_due_minor`),
    CONSTRAINT `loan_installment_check_status` CHECK(`status` IN ('UPCOMING', 'PARTIAL', 'PAID', 'OVERDUE', 'WAIVED')),
    CONSTRAINT `loan_installment_check_payment_state` CHECK((`status` IN ('UPCOMING', 'OVERDUE', 'WAIVED') AND `paid_at` IS NULL) OR (`status` = 'PARTIAL' AND `amount_paid_minor` > 0 AND `amount_paid_minor` < `amount_due_minor` AND `paid_at` IS NOT NULL) OR (`status` = 'PAID' AND `amount_paid_minor` = `amount_due_minor` AND `paid_at` IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE `cash_transaction` (
    `id` integer PRIMARY KEY AUTOINCREMENT,
    `public_id` text NOT NULL,
    `organization_id` text NOT NULL,
    `transaction_number` text NOT NULL,
    `transaction_type` text NOT NULL,
    `direction` text NOT NULL,
    `borrower_id` integer NOT NULL,
    `loan_id` integer NOT NULL,
    `amount_minor` integer NOT NULL,
    `transaction_at` integer DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)) NOT NULL,
    `idempotency_key` text,
    `notes` text,
    `created_by_user_id` text NOT NULL,
    `created_at` integer DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)) NOT NULL,
    CONSTRAINT `cash_transaction_organization_id_public_id_unique` UNIQUE(`organization_id`, `public_id`),
    CONSTRAINT `cash_transaction_organization_id_transaction_number_unique` UNIQUE(`organization_id`, `transaction_number`),
    CONSTRAINT `cash_transaction_organization_id_idempotency_key_unique` UNIQUE(`organization_id`, `idempotency_key`),
    CONSTRAINT `cash_transaction_organization_id_loan_id_type_unique` UNIQUE(`organization_id`, `loan_id`, `transaction_type`),
    CONSTRAINT `cash_transaction_fk_organization` FOREIGN KEY (`organization_id`) REFERENCES `organization`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `cash_transaction_fk_borrower` FOREIGN KEY (`organization_id`, `borrower_id`) REFERENCES `borrower`(`organization_id`, `id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `cash_transaction_fk_loan` FOREIGN KEY (`organization_id`, `loan_id`) REFERENCES `loan`(`organization_id`, `id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `cash_transaction_fk_created_by_member` FOREIGN KEY (`organization_id`, `created_by_user_id`) REFERENCES `member`(`organization_id`, `user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `cash_transaction_check_number` CHECK(length(trim(`transaction_number`)) > 0),
    CONSTRAINT `cash_transaction_check_type_direction` CHECK(`transaction_type` = 'LOAN_RELEASE' AND `direction` = 'CASH_OUT'),
    CONSTRAINT `cash_transaction_check_amount` CHECK(`amount_minor` > 0)
);
--> statement-breakpoint
CREATE INDEX `loan_product_idx_list` ON `loan_product` (`organization_id`, `is_active`, `updated_at` DESC, `id`);
--> statement-breakpoint
CREATE INDEX `loan_idx_list` ON `loan` (`organization_id`, `status`, `created_at` DESC, `id`);
--> statement-breakpoint
CREATE INDEX `loan_idx_borrower_history` ON `loan` (`organization_id`, `borrower_id`, `created_at` DESC, `id`);
--> statement-breakpoint
CREATE INDEX `loan_installment_idx_schedule` ON `loan_installment` (`organization_id`, `loan_id`, `installment_number`);
--> statement-breakpoint
CREATE INDEX `cash_transaction_idx_loan` ON `cash_transaction` (`organization_id`, `loan_id`, `transaction_at` DESC, `id`);
